- name: Ansible Copy Example Local to Remote
  become: yes
  hosts: webservers
  tasks:
    - name: copying file with playbook

      copy:
        src: ~/ansible/index.html
        dest: /var/www/html
        owner: root
        group: root        
        mode: 0755

      notify:
        - restart apache2

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted